### ISSUE TITLE
Doesn't seem to be working for me

### ISSUE THREAD

**Issue by altano** [typicode/cult#17]
Hey There,

Thanks for making this.

I'm getting this error:

```
λ cult gulp watch
[cult] Watching gulpfile.js
[cult] Error, can't find gulp command
```

I have gulp installed globally and locally.  I'm on Windows 8.1... would you like me to investigate or do you know what the issue is?

**Comment by typicode** [comment]
Hi Alan,

It may be related to #15 could you update to v2.0.6 please?

**Comment by altano** [comment]
That got things going but now I'm seeing another issue.  I start a development server (browser-sync and webpack-dev-server) as part of the gulp task.  Cult is killing gulp and restarting it, but my dev server appears to be in a bad state and isn't handling requests.  This is probably not cult's fault... I'll investigate further but close this bug for now.

Thanks!

**Comment by typicode** [comment]
I've noticed that working with servers can be tricky. Feel free to create another issue or reopen this one if you can't make it work. I'll be happy to help.

Basically, cult "should" gracefully stop gulp when reloading but I've only tested this feature on OSX and Linux for the moment. I've created a server task for this in `/example`.
